#!/bin/sh

set -eu

note() {
  echo >&2 "NOTE: $*"
}

die() {
  echo >&2 "ERROR: $*"
  exit 1
}

[ -z "${GITEA_TOKEN:-}" ] && die 'GITEA_TOKEN not set'
[ -z "${GITEA_BASE:-}" ] && die 'GITEA_BASE not set'

# sanity checks; this shouldn't happen if we were called by CI
owner=${CI_REPO_OWNER:-${DRONE_REPO_NAMESPACE:-}}
[ -z "$owner" ] && die 'CI_REPO_OWNER / DRONE_REPO_NAMESPACE not set'

repository=${CI_REPO_NAME:-${DRONE_REPO_NAME:-}}
[ -z "$repository" ] && die 'CI_REPO_NAME / DRONE_REPO_NAME not set'

pull_request=${CI_COMMIT_PULL_REQUEST:-${DRONE_PULL_REQUEST:-}}
[ -z "$pull_request" ] && die 'CI_COMMIT_PULL_REQUEST / DRONE_PULL_REQUEST not set'

if [ -n "${MESSAGE:-}" ]; then
  [ -z "${SUCCESS_MESSAGE:-}" ] || die 'please set either SUCCESS_MESSAGE or MESSAGE'
  [ -z "${FAILURE_MESSAGE:-}" ] || die 'please set either FAILURE_MESSAGE or MESSAGE'
  note 'using text from MESSAGE'
  message="$MESSAGE"
else
  status=${CI_PIPELINE_STATUS:-${DRONE_STAGE_STATUS:-}}

  if [ "$status" = success ]; then
    note 'using text from SUCCESS_MESSAGE'
    message="${SUCCESS_MESSAGE:-}"
  else
    note 'using text from FAILURE_MESSAGE'
    message="${FAILURE_MESSAGE:-}"
  fi
fi

if [ -z "$message" ]; then
  die 'no message was passed; use either of
  message: this text is printed on success of failure
or
  success_message: this text is printed on success
  failure_message: this text is printed on failure'
fi

if [ -f "$message" ]; then
  note "reading message from file $message"
  message=$(cat "$message")
fi

body=$(mktemp)
resp=$(mktemp)

echo "$message" | envsubst | jq --raw-input '{ body: . }' >"$body"

curl \
  --location \
  --silent \
  --show-error \
  --fail-with-body \
  --header "Authorization: token $GITEA_TOKEN" \
  --json "@$body" \
  --output "$resp" \
  "$GITEA_BASE/api/v1/repos/$owner/$repository/issues/$pull_request/comments"

jq --color-output . <"$resp"

rm -f "$body" "$resp"
